global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
chains:
    provider:
        type: cosmos
        value:
            key: default
            chain-id: provider
            rpc-addr: https://provider-rpc.ztake.org:443/
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 2
            gas-prices: 0.025uprov
            min-gas-amount: 0
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    sputnik:
        type: cosmos
        value:
            key: default
            chain-id: sputnik
            rpc-addr: https://sputnik-rpc.ztake.org:443/
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 2
            gas-prices: 0.01unik
            min-gas-amount: 0
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    hero:
        type: cosmos
        value:
            key: default
            chain-id: hero-1
            rpc-addr: http://127.0.0.1:26657
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 2
            gas-prices: 0.01uhero
            min-gas-amount: 0
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
paths:
    provider-sputnik:
        src:
            chain-id: provider
            client-id: 07-tendermint-0
            connection-id: connection-0
        dst:
            chain-id: sputnik
            client-id: 07-tendermint-0
            connection-id: connection-0
        src-channel-filter:
            rule: "allowlist"
            channel-list: [channel-0,channel-1]
    provider-hero:
        src:
            chain-id: provider
            client-id: 07-tendermint-3
            connection-id: connection-14
        dst:
            chain-id: hero-1
            client-id: 07-tendermint-0
            connection-id: connection-0
        src-channel-filter:
            rule: "allowlist"
            channel-list: [channel-8,channel-9]
